name: Render resume.pdf
on: push
jobs:
  render-resume:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: typst compile resume.typ --font-path fonts
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: resume.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: resume.pdf
